#!/usr/bin/python
import socket
import struct
import base64
def swap(a,b):
    t=a
    a=b
    b=t

def check_diff(a, b):
    if len(a) != len(b):
        return -1
    count = 0
    for i in range(0, len(a)):
        if a[i] != b[i]:
            count += 1
        if count > 1024:
            return -1
    return 1
#HOST='127.0.0.1'
HOST='117.50.13.213'
PORT=12345
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST,PORT))



image=open("basque-shepherd-dog (1).jpg","rb").read();


for i in range(1,(len(image)/4)):
    swap(image[i],image[i+2])
    swap(image[i+1],image[i+3])

print(image[0:7])
#print struct.pack('>I',image);
#print base64.b64encode(image)
encode_image=base64.b64encode(image);
#encode=open("str_en_f.txt","rb").read();
Expected_L=62256;
L = len(encode_image);
i = 1
while (Expected_L>=0):

    j = i + 128
    if (j >= L - 1):
        j = L + 1
        Flag = 0

    #print(encode_image[i - 1:j - 1])
    Expected_L-=128
    i += 128
print(check_diff(base64.b64decode(encode_image),image))
#print(check_diff(base64.b64decode(base64.b64encode(image)),image))

#print len(base64.b64encode(image));
while 1:
       data='';
       data=s.recv(1024)
       if not data:
           break
       else:
           print (data);
           if data=='no\n':
               N=0;
               break

       #cmd = raw_input("Please input cmd:")

       #for i in range(1,61):
          # s.sendall('\n');


           Expected_L = 62000;
           L = len(encode_image);
           i = 1;
           Flag = 1;
           while (Expected_L >= 0):

                j = i + 1024;
                if (j >= L - 1):
                    j = L + 1;
                    Flag = 0;
                data=encode_image[i-1:j-1];

                s.send(bytes(data));
                Expected_L -= 1024
                i += 1024;


       print 'sent'
s.close()